// Generated by scripts/export_actual_data.py from the "actual data" tab of
// "New Class IX FMS CCWS 26-27.xlsx". Do not edit by hand: update the sheet and re-run the script.
// Aggregate student counts per score band only; no individual student records.
import type { ActualDataset } from './milestoneBands';

export const CLASS_IX_ACTUAL_DATA: ActualDataset = {
  "source": {
    "workbook": "New Class IX FMS CCWS 26-27.xlsx",
    "tab": "actual data",
    "sheetSavedOn": "2026-09-22"
  },
  "school": "Cambridge Court World School",
  "academicYear": "2026-27",
  "wholeClass": {
    "id": "wholeClass",
    "label": "Whole class",
    "sheetTitle": "VIII",
    "results": {
      "viiiHalfYearly": {
        "b95": 2,
        "b90": 10,
        "b85": 21,
        "b80": 21,
        "b75": 26,
        "b70": 15,
        "b65": 21,
        "b60": 15,
        "b55": 14,
        "b50": 10,
        "b45": 5,
        "b40": 7,
        "b33": 2,
        "below33": 5
      },
      "preMid": {
        "b95": 3,
        "b90": 9,
        "b85": 17,
        "b80": 20,
        "b75": 18,
        "b70": 29,
        "b65": 20,
        "b60": 7,
        "b55": 13,
        "b50": 10,
        "b45": 4,
        "b40": 3,
        "b33": 7,
        "below33": 1
      },
      "midTerm": {
        "b95": 8,
        "b90": 13,
        "b85": 20,
        "b80": 10,
        "b75": 15,
        "b70": 15,
        "b65": 15,
        "b60": 15,
        "b55": 10,
        "b50": 10,
        "b45": 4,
        "b40": 4,
        "b33": 4,
        "below33": 3
      }
    }
  },
  "subjects": [
    {
      "id": "english",
      "label": "English",
      "sheetTitle": "VIII - ENGLISH",
      "results": {
        "viiiHalfYearly": {
          "b95": 2,
          "b90": 14,
          "b85": 20,
          "b80": 22,
          "b75": 18,
          "b70": 17,
          "b65": 18,
          "b60": 10,
          "b55": 15,
          "b50": 8,
          "b45": 3,
          "b40": 5,
          "b33": 4,
          "below33": 4
        }
      }
    },
    {
      "id": "hindi",
      "label": "Hindi",
      "sheetTitle": "VIII- HINDI",
      "results": {
        "viiiHalfYearly": {
          "b95": 1,
          "b90": 4,
          "b85": 16,
          "b80": 11,
          "b75": 21,
          "b70": 23,
          "b65": 21,
          "b60": 13,
          "b55": 11,
          "b50": 12,
          "b45": 10,
          "b40": 10,
          "b33": 5,
          "below33": 2
        }
      }
    },
    {
      "id": "sanskrit",
      "label": "Sanskrit",
      "sheetTitle": "VIII- SANSKRIT",
      "results": {
        "viiiHalfYearly": {
          "b95": 4,
          "b90": 7,
          "b85": 8,
          "b80": 11,
          "b75": 6,
          "b70": 2,
          "b65": 13,
          "b60": 3,
          "b55": 2,
          "b50": 5,
          "b45": 4,
          "b40": 9,
          "b33": 1,
          "below33": 1
        }
      }
    },
    {
      "id": "french",
      "label": "French",
      "sheetTitle": "VIII- FRENCH",
      "results": {
        "viiiHalfYearly": {
          "b95": 6,
          "b90": 14,
          "b85": 6,
          "b80": 18,
          "b75": 9,
          "b70": 8,
          "b65": 7,
          "b60": 2,
          "b55": 3,
          "b50": 6,
          "b45": 2,
          "b40": 0,
          "b33": 0,
          "below33": 0
        }
      }
    },
    {
      "id": "maths",
      "label": "Mathematics",
      "sheetTitle": "VIII- MATHS",
      "results": {
        "viiiHalfYearly": {
          "b95": 6,
          "b90": 7,
          "b85": 8,
          "b80": 17,
          "b75": 16,
          "b70": 9,
          "b65": 11,
          "b60": 9,
          "b55": 9,
          "b50": 14,
          "b45": 16,
          "b40": 9,
          "b33": 15,
          "below33": 18
        }
      }
    },
    {
      "id": "science",
      "label": "Science",
      "sheetTitle": "VIII- SCIENCE",
      "results": {
        "viiiHalfYearly": {
          "b95": 5,
          "b90": 21,
          "b85": 33,
          "b80": 20,
          "b75": 26,
          "b70": 12,
          "b65": 12,
          "b60": 3,
          "b55": 11,
          "b50": 6,
          "b45": 3,
          "b40": 3,
          "b33": 2,
          "below33": 3
        }
      }
    },
    {
      "id": "socialScience",
      "label": "Social Science",
      "sheetTitle": "VIII- SOCIAL SCIENCE",
      "results": {
        "viiiHalfYearly": {
          "b95": 2,
          "b90": 13,
          "b85": 14,
          "b80": 17,
          "b75": 19,
          "b70": 17,
          "b65": 16,
          "b60": 14,
          "b55": 11,
          "b50": 9,
          "b45": 9,
          "b40": 6,
          "b33": 8,
          "below33": 5
        }
      }
    },
    {
      "id": "computer",
      "label": "Computer",
      "sheetTitle": "VIII- Computer",
      "results": {
        "viiiHalfYearly": {
          "b95": 26,
          "b90": 33,
          "b85": 32,
          "b80": 23,
          "b75": 17,
          "b70": 7,
          "b65": 12,
          "b60": 3,
          "b55": 0,
          "b50": 0,
          "b45": 0,
          "b40": 0,
          "b33": 0,
          "below33": 7
        }
      }
    }
  ]
};
