/**
 * Score bands, exams and data types for the Class IX results dashboard.
 *
 * The figures themselves live in class9ActualData.ts, generated by scripts/export_actual_data.py
 * from the "actual data" tab of the FMS workbook. Aggregate counts only, no student records.
 */

/** Single score bands exactly as the sheet lists them, highest first */
export type FineBandId =
  | 'b95' | 'b90' | 'b85' | 'b80' | 'b75' | 'b70' | 'b65'
  | 'b60' | 'b55' | 'b50' | 'b45' | 'b40' | 'b33' | 'below33';

export type FineCounts = Record<FineBandId, number>;

/** Chart bands: the sheet's bands merged into five so a single-hue ramp stays readable */
export type BandId = 'b95' | 'b90' | 'b80' | 'b70' | 'below70';

export interface ScoreBand {
  id: BandId;
  /** Short label for axes and table headers */
  label: string;
  /** Longer label for tooltips, legends and screen readers */
  description: string;
  /**
   * CCWS maroon ramp, validated with the dataviz ordinal check. Light mode: darker = higher score
   * (the site's lightest step #ECC2CC is deepened to #E3A6B4 to clear 2:1 on white). Dark mode:
   * brighter = higher score.
   */
  fill: { light: string; dark: string };
  /** Text colour for labels drawn inside a fill of this band */
  ink: { light: string; dark: string };
}

const INK_ON_DARK = '#FFFFFF';
const INK_ON_LIGHT = '#2A211C';

/** Highest band first. Order drives every chart bar and table column. */
export const SCORE_BANDS: ScoreBand[] = [
  { id: 'b95', label: '95+', description: '95% and above', fill: { light: '#6A0222', dark: '#F5C9D3' }, ink: { light: INK_ON_DARK, dark: INK_ON_LIGHT } },
  { id: 'b90', label: '90-94', description: '90% to 94.9%', fill: { light: '#960330', dark: '#E895A9' }, ink: { light: INK_ON_DARK, dark: INK_ON_LIGHT } },
  { id: 'b80', label: '80-89', description: '80% to 89.9%', fill: { light: '#BA3C5D', dark: '#D06580' }, ink: { light: INK_ON_DARK, dark: INK_ON_LIGHT } },
  { id: 'b70', label: '70-79', description: '70% to 79.9%', fill: { light: '#D87F95', dark: '#B03C5B' }, ink: { light: INK_ON_LIGHT, dark: INK_ON_DARK } },
  { id: 'below70', label: '<70', description: 'Below 70%', fill: { light: '#E3A6B4', dark: '#8C2542' }, ink: { light: INK_ON_LIGHT, dark: INK_ON_DARK } },
];

/** The sheet's single bands, highest first, and the chart band each one rolls up into */
export const FINE_BANDS: { id: FineBandId; label: string; chartBand: BandId }[] = [
  { id: 'b95', label: '95 and above', chartBand: 'b95' },
  { id: 'b90', label: '90-94', chartBand: 'b90' },
  { id: 'b85', label: '85-89', chartBand: 'b80' },
  { id: 'b80', label: '80-84', chartBand: 'b80' },
  { id: 'b75', label: '75-79', chartBand: 'b70' },
  { id: 'b70', label: '70-74', chartBand: 'b70' },
  { id: 'b65', label: '65-69', chartBand: 'below70' },
  { id: 'b60', label: '60-64', chartBand: 'below70' },
  { id: 'b55', label: '55-59', chartBand: 'below70' },
  { id: 'b50', label: '50-54', chartBand: 'below70' },
  { id: 'b45', label: '45-49', chartBand: 'below70' },
  { id: 'b40', label: '40-44', chartBand: 'below70' },
  { id: 'b33', label: '33-39', chartBand: 'below70' },
  { id: 'below33', label: 'Below 33', chartBand: 'below70' },
];

/** "N and above" rows, as the sheet groups them; each counts its band and every band above */
export const THRESHOLDS: { label: string; through: FineBandId }[] = [
  { label: '95 and above', through: 'b95' },
  { label: '90 and above', through: 'b90' },
  { label: '80 and above', through: 'b80' },
  { label: '70 and above', through: 'b70' },
  { label: '60 and above', through: 'b60' },
  { label: '50 and above', through: 'b50' },
  { label: '40 and above', through: 'b40' },
  { label: '33 and above', through: 'b33' },
];

/** Exams in the sheet, oldest first. The sheet column each one comes from is noted. */
export type ExamId = 'viiiHalfYearly' | 'preMid' | 'midTerm';

export const EXAMS: { id: ExamId; label: string; name: string; shortLabel: string; sheetColumn: string }[] = [
  { id: 'viiiHalfYearly', label: 'Class VIII Half-Yearly Examination', name: 'Class VIII Half-Yearly', shortLabel: 'VIII Half-Yearly', sheetColumn: 'B' },
  { id: 'preMid', label: 'Pre-Mid Term Examination', name: 'Pre-Mid Term', shortLabel: 'Pre-Mid', sheetColumn: 'V' },
  { id: 'midTerm', label: 'Mid Term Examination', name: 'Mid Term', shortLabel: 'Mid Term', sheetColumn: 'AA' },
];

/** One block of the sheet (the whole class, or one subject) and the exams it has figures for */
export interface ActualGroup {
  id: string;
  label: string;
  sheetTitle: string;
  results: Partial<Record<ExamId, FineCounts>>;
}

export interface ActualDataset {
  source: { workbook: string; tab: string; sheetSavedOn: string | null };
  school: string;
  academicYear: string;
  wholeClass: ActualGroup;
  subjects: ActualGroup[];
}

/** A row for the band tables and charts: a group's counts rolled up into the five chart bands */
export interface ClassBandCounts {
  classId: string;
  label: string;
  counts: Record<BandId, number>;
}
